print(True)
print(False)
print(1)
print(2.1)
print('Thiago')
print("Faby")
print([2, 4, 6, 8, 10])
print({'nome':'Fabiana', 'idade': 30})
print(['corolla', 'jeep', 'bmw'])
print({'nome': 'Thiago', 'habilitado': True, 'nota': 9.8})
